version: "3.9"

services:
  mongo:
    image: mongo:7.0.14
    container_name: mongo
    restart: unless-stopped
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: admin
      MONGO_INITDB_DATABASE: mydb
    volumes:
      - mongo_data:/data/db
    command: ["--bind_ip_all"]
    healthcheck:
      test: ["CMD-SHELL", "mongosh -u admin -p admin --authenticationDatabase admin --quiet --eval 'db.adminCommand({ ping: 1 })'"]
      interval: 10s
      timeout: 5s
      retries: 8

volumes:
  mongo_data:
